### ISSUE TITLE
ERROR 505 - FORGET PASSWORD ERROR

### ISSUE THREAD

**Issue by Ed-df** [gabzon/onlinedance#2]
Erreur au niveau du password.
Quand on clique sur "forgot your password" dans le login. on a une erreur 505

![Screenshot 2021-05-21 at 12 40 04](https://user-images.githubusercontent.com/84179539/119125225-d256cd80-ba31-11eb-8041-831825cc11fd.png)

**Comment by gabzon** [comment]
working with next v.
